---
driver:
  name: vagrant
  synced_folders:
    - ["./", "/vagrant", disabled: false]
provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-7.0
  - name: debian-7.7

suites:
  - name: debian
    excludes: ["centos-7.0"]
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[golang]
      - recipe[golang::packages]
      - recipe[setup_go]
      - recipe[ceph_micro]
    attributes:
      go:
        packages: ["github.com/sathlan/libradosgo"]
  - name: rhel
    excludes: ["ubuntu-12.04", "ubuntu-14.04", "debian-7.7"]
    run_list:
      - recipe[build-essential]
      - recipe[golang]
      - recipe[golang::packages]
      - recipe[setup_go]
      - recipe[ceph_micro]
    attributes:
      go:
        packages: ["github.com/sathlan/libradosgo"]
